// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var zoneModels = ZoneModels.FromJson(jsonString);

namespace QuickType
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ZoneModels
    {
        [JsonProperty("$schema")]
        public Uri Schema { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("properties")]
        public ZoneModelsProperties Properties { get; set; }

        [JsonProperty("required")]
        public string[] ZoneModelsRequired { get; set; }
    }

    public partial class ZoneModelsProperties
    {
        [JsonProperty("zoneId")]
        public Description ZoneId { get; set; }

        [JsonProperty("name")]
        public Description Name { get; set; }

        [JsonProperty("enabled")]
        public Description Enabled { get; set; }

        [JsonProperty("difficulty")]
        public Difficulty Difficulty { get; set; }

        [JsonProperty("description")]
        public Description Description { get; set; }

        [JsonProperty("location")]
        public Location Location { get; set; }

        [JsonProperty("entry")]
        public Entry Entry { get; set; }

        [JsonProperty("mobs")]
        public Mobs Mobs { get; set; }

        [JsonProperty("boss")]
        public Boss Boss { get; set; }

        [JsonProperty("loot")]
        public Loot Loot { get; set; }

        [JsonProperty("schematic")]
        public Schematic Schematic { get; set; }

        [JsonProperty("effects")]
        public Effects Effects { get; set; }

        [JsonProperty("permissions")]
        public Permissions Permissions { get; set; }

        [JsonProperty("audit")]
        public Audit Audit { get; set; }
    }

    public partial class Audit
    {
        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("properties")]
        public AuditProperties Properties { get; set; }

        [JsonProperty("required")]
        public string[] AuditRequired { get; set; }
    }

    public partial class AuditProperties
    {
        [JsonProperty("createdBy")]
        public CreatedBy CreatedBy { get; set; }

        [JsonProperty("createdAt")]
        public CreatedAt CreatedAt { get; set; }

        [JsonProperty("logId")]
        public CreatedBy LogId { get; set; }
    }

    public partial class CreatedAt
    {
        [JsonProperty("type")]
        public TypeEnum Type { get; set; }

        [JsonProperty("format")]
        public string Format { get; set; }
    }

    public partial class CreatedBy
    {
        [JsonProperty("type")]
        public TypeEnum Type { get; set; }
    }

    public partial class Boss
    {
        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("properties")]
        public BossProperties Properties { get; set; }

        [JsonProperty("required")]
        public string[] BossRequired { get; set; }
    }

    public partial class BossProperties
    {
        [JsonProperty("bossName")]
        public CreatedBy BossName { get; set; }

        [JsonProperty("bossLevel")]
        public CreatedBy BossLevel { get; set; }

        [JsonProperty("respawn")]
        public Respawn Respawn { get; set; }

        [JsonProperty("reward")]
        public Reward Reward { get; set; }

        [JsonProperty("validation")]
        public Validation Validation { get; set; }
    }

    public partial class Respawn
    {
        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("properties")]
        public RespawnProperties Properties { get; set; }

        [JsonProperty("required")]
        public string[] RespawnRequired { get; set; }
    }

    public partial class RespawnProperties
    {
        [JsonProperty("type")]
        public TypeClass Type { get; set; }

        [JsonProperty("value")]
        public CreatedBy Value { get; set; }
    }

    public partial class TypeClass
    {
        [JsonProperty("type")]
        public TypeEnum Type { get; set; }

        [JsonProperty("enum")]
        public string[] Enum { get; set; }
    }

    public partial class Reward
    {
        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("items")]
        public RewardItems Items { get; set; }
    }

    public partial class RewardItems
    {
        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("properties")]
        public PurpleProperties Properties { get; set; }

        [JsonProperty("required")]
        public string[] ItemsRequired { get; set; }
    }

    public partial class PurpleProperties
    {
        [JsonProperty("itemName")]
        public CreatedBy ItemName { get; set; }

        [JsonProperty("count")]
        public CreatedBy Count { get; set; }

        [JsonProperty("chance")]
        public CreatedBy Chance { get; set; }
    }

    public partial class Validation
    {
        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("properties")]
        public ValidationProperties Properties { get; set; }

        [JsonProperty("required")]
        public string[] ValidationRequired { get; set; }
    }

    public partial class ValidationProperties
    {
        [JsonProperty("requiresDevApproval")]
        public CreatedBy RequiresDevApproval { get; set; }

        [JsonProperty("requiresAdmin")]
        public CreatedBy RequiresAdmin { get; set; }
    }

    public partial class Description
    {
        [JsonProperty("type")]
        public TypeEnum Type { get; set; }

        [JsonProperty("description")]
        public string DescriptionDescription { get; set; }
    }

    public partial class Difficulty
    {
        [JsonProperty("type")]
        public TypeEnum Type { get; set; }

        [JsonProperty("enum")]
        public string[] Enum { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }
    }

    public partial class Effects
    {
        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("properties")]
        public EffectsProperties Properties { get; set; }

        [JsonProperty("required")]
        public string[] EffectsRequired { get; set; }
    }

    public partial class EffectsProperties
    {
        [JsonProperty("ui")]
        public Ui Ui { get; set; }

        [JsonProperty("glow")]
        public Glow Glow { get; set; }

        [JsonProperty("map")]
        public Map Map { get; set; }
    }

    public partial class Glow
    {
        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("properties")]
        public GlowProperties Properties { get; set; }

        [JsonProperty("required")]
        public string[] GlowRequired { get; set; }
    }

    public partial class GlowProperties
    {
        [JsonProperty("enterGlow")]
        public CreatedBy EnterGlow { get; set; }

        [JsonProperty("exitGlow")]
        public CreatedBy ExitGlow { get; set; }
    }

    public partial class Map
    {
        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("properties")]
        public MapProperties Properties { get; set; }

        [JsonProperty("required")]
        public string[] MapRequired { get; set; }
    }

    public partial class MapProperties
    {
        [JsonProperty("enterMapEffect")]
        public CreatedBy EnterMapEffect { get; set; }

        [JsonProperty("exitMapEffect")]
        public CreatedBy ExitMapEffect { get; set; }
    }

    public partial class Ui
    {
        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("properties")]
        public UiProperties Properties { get; set; }

        [JsonProperty("required")]
        public string[] UiRequired { get; set; }
    }

    public partial class UiProperties
    {
        [JsonProperty("enterEffect")]
        public CreatedBy EnterEffect { get; set; }

        [JsonProperty("exitEffect")]
        public CreatedBy ExitEffect { get; set; }

        [JsonProperty("hudMessage")]
        public CreatedBy HudMessage { get; set; }
    }

    public partial class Entry
    {
        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("properties")]
        public EntryProperties Properties { get; set; }

        [JsonProperty("required")]
        public string[] EntryRequired { get; set; }
    }

    public partial class EntryProperties
    {
        [JsonProperty("onEnter")]
        public OnEnter OnEnter { get; set; }

        [JsonProperty("onExit")]
        public OnExit OnExit { get; set; }
    }

    public partial class OnEnter
    {
        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("properties")]
        public OnEnterProperties Properties { get; set; }

        [JsonProperty("required")]
        public string[] OnEnterRequired { get; set; }
    }

    public partial class OnEnterProperties
    {
        [JsonProperty("giveGear")]
        public CreatedBy GiveGear { get; set; }

        [JsonProperty("gearList")]
        public GearList GearList { get; set; }

        [JsonProperty("overrideBlood")]
        public CreatedBy OverrideBlood { get; set; }

        [JsonProperty("bloodType")]
        public CreatedBy BloodType { get; set; }

        [JsonProperty("uiEffect")]
        public CreatedBy UiEffect { get; set; }

        [JsonProperty("glowEffect")]
        public CreatedBy GlowEffect { get; set; }

        [JsonProperty("mapEffect")]
        public CreatedBy MapEffect { get; set; }

        [JsonProperty("message")]
        public CreatedBy Message { get; set; }
    }

    public partial class GearList
    {
        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("items")]
        public GearListItems Items { get; set; }
    }

    public partial class GearListItems
    {
        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("properties")]
        public FluffyProperties Properties { get; set; }

        [JsonProperty("required")]
        public string[] ItemsRequired { get; set; }
    }

    public partial class FluffyProperties
    {
        [JsonProperty("itemName")]
        public CreatedBy ItemName { get; set; }

        [JsonProperty("count")]
        public CreatedBy Count { get; set; }

        [JsonProperty("equip")]
        public CreatedBy Equip { get; set; }
    }

    public partial class OnExit
    {
        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("properties")]
        public OnExitProperties Properties { get; set; }

        [JsonProperty("required")]
        public string[] OnExitRequired { get; set; }
    }

    public partial class OnExitProperties
    {
        [JsonProperty("removeGear")]
        public CreatedBy RemoveGear { get; set; }

        [JsonProperty("restoreBlood")]
        public CreatedBy RestoreBlood { get; set; }

        [JsonProperty("uiEffect")]
        public CreatedBy UiEffect { get; set; }

        [JsonProperty("glowEffect")]
        public CreatedBy GlowEffect { get; set; }

        [JsonProperty("mapEffect")]
        public CreatedBy MapEffect { get; set; }

        [JsonProperty("message")]
        public CreatedBy Message { get; set; }
    }

    public partial class Location
    {
        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("properties")]
        public LocationProperties Properties { get; set; }

        [JsonProperty("required")]
        public string[] LocationRequired { get; set; }
    }

    public partial class LocationProperties
    {
        [JsonProperty("center")]
        public Center Center { get; set; }

        [JsonProperty("radius")]
        public CreatedBy Radius { get; set; }

        [JsonProperty("bounds")]
        public Bounds Bounds { get; set; }
    }

    public partial class Bounds
    {
        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("properties")]
        public BoundsProperties Properties { get; set; }

        [JsonProperty("required")]
        public string[] BoundsRequired { get; set; }
    }

    public partial class BoundsProperties
    {
        [JsonProperty("min")]
        public Center Min { get; set; }

        [JsonProperty("max")]
        public Center Max { get; set; }
    }

    public partial class Center
    {
        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("properties")]
        public CenterProperties Properties { get; set; }

        [JsonProperty("required")]
        public RequiredElement[] CenterRequired { get; set; }
    }

    public partial class CenterProperties
    {
        [JsonProperty("x")]
        public CreatedBy X { get; set; }

        [JsonProperty("y")]
        public CreatedBy Y { get; set; }

        [JsonProperty("z")]
        public CreatedBy Z { get; set; }
    }

    public partial class Loot
    {
        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("properties")]
        public LootProperties Properties { get; set; }

        [JsonProperty("required")]
        public string[] LootRequired { get; set; }
    }

    public partial class LootProperties
    {
        [JsonProperty("chests")]
        public Chests Chests { get; set; }

        [JsonProperty("dropTables")]
        public DropTables DropTables { get; set; }
    }

    public partial class Chests
    {
        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("items")]
        public ChestsItems Items { get; set; }
    }

    public partial class ChestsItems
    {
        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("properties")]
        public TentacledProperties Properties { get; set; }

        [JsonProperty("required")]
        public string[] ItemsRequired { get; set; }
    }

    public partial class TentacledProperties
    {
        [JsonProperty("position")]
        public Center Position { get; set; }

        [JsonProperty("lootTable")]
        public Reward LootTable { get; set; }
    }

    public partial class DropTables
    {
        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("items")]
        public DropTablesItems Items { get; set; }
    }

    public partial class DropTablesItems
    {
        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("properties")]
        public StickyProperties Properties { get; set; }

        [JsonProperty("required")]
        public string[] ItemsRequired { get; set; }
    }

    public partial class StickyProperties
    {
        [JsonProperty("tableName")]
        public CreatedBy TableName { get; set; }

        [JsonProperty("items")]
        public Reward Items { get; set; }
    }

    public partial class Mobs
    {
        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("items")]
        public MobsItems Items { get; set; }
    }

    public partial class MobsItems
    {
        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("properties")]
        public IndigoProperties Properties { get; set; }

        [JsonProperty("required")]
        public string[] ItemsRequired { get; set; }
    }

    public partial class IndigoProperties
    {
        [JsonProperty("mobName")]
        public CreatedBy MobName { get; set; }

        [JsonProperty("count")]
        public CreatedBy Count { get; set; }

        [JsonProperty("spawnRate")]
        public CreatedBy SpawnRate { get; set; }

        [JsonProperty("respawnInterval")]
        public CreatedBy RespawnInterval { get; set; }
    }

    public partial class Permissions
    {
        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("properties")]
        public PermissionsProperties Properties { get; set; }

        [JsonProperty("required")]
        public string[] PermissionsRequired { get; set; }
    }

    public partial class PermissionsProperties
    {
        [JsonProperty("requiresDevApproval")]
        public CreatedBy RequiresDevApproval { get; set; }

        [JsonProperty("requiresAdmin")]
        public CreatedBy RequiresAdmin { get; set; }

        [JsonProperty("requiresSnapshot")]
        public CreatedBy RequiresSnapshot { get; set; }
    }

    public partial class Schematic
    {
        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("properties")]
        public SchematicProperties Properties { get; set; }

        [JsonProperty("required")]
        public string[] SchematicRequired { get; set; }
    }

    public partial class SchematicProperties
    {
        [JsonProperty("enabled")]
        public CreatedBy Enabled { get; set; }

        [JsonProperty("schematicId")]
        public CreatedBy SchematicId { get; set; }

        [JsonProperty("saveOnComplete")]
        public CreatedBy SaveOnComplete { get; set; }

        [JsonProperty("autoShareToLog")]
        public CreatedBy AutoShareToLog { get; set; }
    }

    public enum TypeEnum { Boolean, Integer, Number, String };

    public enum RequiredElement { X, Y, Z };

    public partial class ZoneModels
    {
        public static ZoneModels FromJson(string json) => JsonConvert.DeserializeObject<ZoneModels>(json, QuickType.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this ZoneModels self) => JsonConvert.SerializeObject(self, QuickType.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                TypeEnumConverter.Singleton,
                RequiredElementConverter.Singleton,
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class TypeEnumConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(TypeEnum) || t == typeof(TypeEnum?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "boolean":
                    return TypeEnum.Boolean;
                case "integer":
                    return TypeEnum.Integer;
                case "number":
                    return TypeEnum.Number;
                case "string":
                    return TypeEnum.String;
            }
            throw new Exception("Cannot unmarshal type TypeEnum");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (TypeEnum)untypedValue;
            switch (value)
            {
                case TypeEnum.Boolean:
                    serializer.Serialize(writer, "boolean");
                    return;
                case TypeEnum.Integer:
                    serializer.Serialize(writer, "integer");
                    return;
                case TypeEnum.Number:
                    serializer.Serialize(writer, "number");
                    return;
                case TypeEnum.String:
                    serializer.Serialize(writer, "string");
                    return;
            }
            throw new Exception("Cannot marshal type TypeEnum");
        }

        public static readonly TypeEnumConverter Singleton = new TypeEnumConverter();
    }

    internal class RequiredElementConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(RequiredElement) || t == typeof(RequiredElement?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "x":
                    return RequiredElement.X;
                case "y":
                    return RequiredElement.Y;
                case "z":
                    return RequiredElement.Z;
            }
            throw new Exception("Cannot unmarshal type RequiredElement");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (RequiredElement)untypedValue;
            switch (value)
            {
                case RequiredElement.X:
                    serializer.Serialize(writer, "x");
                    return;
                case RequiredElement.Y:
                    serializer.Serialize(writer, "y");
                    return;
                case RequiredElement.Z:
                    serializer.Serialize(writer, "z");
                    return;
            }
            throw new Exception("Cannot marshal type RequiredElement");
        }

        public static readonly RequiredElementConverter Singleton = new RequiredElementConverter();
    }
}
